/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/core/useGLTF";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("../../../barcelona.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID3.geometry} />
        <mesh material={materials.material_0} geometry={nodes.ID3_1.geometry} />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID17.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID17_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID25.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID25_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID33.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID33_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID41.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID41_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID49.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID49_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID57.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID57_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID65.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID65_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID73.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID73_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID81.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID81_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID89.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID89_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID97.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID97_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID105.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID105_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID113.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID113_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID121.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID121_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID129.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID129_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID137.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID137_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID145.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID145_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID153.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID153_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID161.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID161_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID169.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID169_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID177.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID177_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID185.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID185_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID193.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID193_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID201.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID201_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID209.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID209_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID217.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID217_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID225.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID225_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID233.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID233_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID241.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID241_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID249.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID249_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID257.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID257_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID265.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID265_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID273.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID273_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID281.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID281_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID289.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID289_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID297.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID297_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID305.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID305_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID313.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID313_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID321.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID321_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID329.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID329_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID337.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID337_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID345.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID345_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID353.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID353_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID361.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID361_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID369.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID369_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID377.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID377_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID385.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID385_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID393.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID393_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID401.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID401_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID409.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID409_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID417.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID417_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID425.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID425_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID433.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID433_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID441.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID441_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID449.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID449_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID457.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID457_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID465.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID465_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID473.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID473_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID481.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID481_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID489.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID489_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID497.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID497_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID505.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID505_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID513.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID513_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID521.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID521_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID529.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID529_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID537.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID537_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID545.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID545_1.geometry}
        />
      </group>
      <group position={[-0.5, -0.62, 0.5]} scale={[0.04, 0.04, 0.04]}>
        <mesh material={materials.material} geometry={nodes.ID553.geometry} />
        <mesh
          material={materials.material_0}
          geometry={nodes.ID553_1.geometry}
        />
      </group>
    </group>
  );
}

useGLTF.preload("../../../barcelona.glb");
