/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/core/useGLTF";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("../../../togo.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={[0.03, 0.03, 0.03]}>
        <mesh
          material={materials.Leather_Seamless_Texture__6690}
          geometry={nodes.LARGE_SETTEE.geometry}
          position={[-15.04, -6.34, 11.52]}
          scale={[0.42, 0.42, 0.42]}
        />
        <mesh
          material={materials.Leather_Seamless_Texture__6690}
          geometry={nodes.LARGE_SETTEE001.geometry}
          position={[-15.97, -6.34, 11.52]}
          scale={[0.42, 0.42, 0.42]}
        />
        <mesh
          material={materials.Leather_Seamless_Texture__6690}
          geometry={nodes.LARGE_SETTEE002.geometry}
          position={[-15.97, -6.34, 11.52]}
          scale={[0.42, 0.42, 0.42]}
        />
        <mesh
          material={materials.Leather_Seamless_Texture__6690}
          geometry={nodes.LARGE_SETTEE003.geometry}
          position={[-15.97, -6.34, 11.52]}
          scale={[0.42, 0.42, 0.42]}
        />
        <mesh
          material={materials.Leather_Seamless_Texture__6690}
          geometry={nodes.LARGE_SETTEE004.geometry}
          position={[-15.97, -6.34, 11.52]}
          scale={[0.42, 0.42, 0.42]}
        />
        <mesh
          material={materials.Leather_Seamless_Texture__6690}
          geometry={nodes.LARGE_SETTEE005.geometry}
          position={[-15.97, -6.34, 11.52]}
          scale={[0.42, 0.42, 0.42]}
        />
        <mesh
          material={materials.Leather_Seamless_Texture__6690}
          geometry={nodes.LARGE_SETTEE006.geometry}
          position={[-15.97, -6.34, 11.52]}
          scale={[0.42, 0.42, 0.42]}
        />
        <mesh
          material={materials.Leather_Seamless_Texture__6690}
          geometry={nodes.LARGE_SETTEE007.geometry}
          position={[-15.97, -6.34, 11.52]}
          scale={[0.42, 0.42, 0.42]}
        />
        <mesh
          material={materials.Leather_Seamless_Texture__6690}
          geometry={nodes.LARGE_SETTEE008.geometry}
          position={[-15.97, -6.34, 11.52]}
          scale={[0.42, 0.42, 0.42]}
        />
        <mesh
          material={materials.Leather_Seamless_Texture__6690}
          geometry={nodes.LARGE_SETTEE009.geometry}
          position={[-15.97, -6.34, 11.52]}
          scale={[0.42, 0.42, 0.42]}
        />
        <mesh
          material={materials.Leather_Seamless_Texture__6690}
          geometry={nodes.LARGE_SETTEE010.geometry}
          position={[-15.97, -6.34, 11.52]}
          scale={[0.42, 0.42, 0.42]}
        />
        <mesh
          material={materials.Leather_Seamless_Texture__6690}
          geometry={nodes.LARGE_SETTEE011.geometry}
          position={[-15.97, -6.34, 11.52]}
          scale={[0.42, 0.42, 0.42]}
        />
        <mesh
          material={materials.Leather_Seamless_Texture__6690}
          geometry={nodes.LARGE_SETTEE012.geometry}
          position={[-15.97, -6.34, 11.52]}
          scale={[0.42, 0.42, 0.42]}
        />
        <mesh
          material={materials.Leather_Seamless_Texture__6690}
          geometry={nodes.LARGE_SETTEE013.geometry}
          position={[-15.97, -6.34, 11.52]}
          scale={[0.42, 0.42, 0.42]}
        />
        <mesh
          material={materials.Leather_Seamless_Texture__6690}
          geometry={nodes.LARGE_SETTEE014.geometry}
          position={[-15.97, -6.34, 11.52]}
          scale={[0.42, 0.42, 0.42]}
        />
        <mesh
          material={materials.Leather_Seamless_Texture__6690}
          geometry={nodes.LARGE_SETTEE015.geometry}
          position={[-15.97, -6.34, 11.52]}
          scale={[0.42, 0.42, 0.42]}
        />
        <mesh
          material={materials.Leather_Seamless_Texture__6690}
          geometry={nodes.LARGE_SETTEE016.geometry}
          position={[-15.97, -6.34, 11.52]}
          scale={[0.42, 0.42, 0.42]}
        />
        <mesh
          material={materials.Leather_Seamless_Texture__6690}
          geometry={nodes.LARGE_SETTEE017.geometry}
          position={[-15.97, -6.34, 11.52]}
          scale={[0.42, 0.42, 0.42]}
        />
        <mesh
          material={materials.Leather_Seamless_Texture__6690}
          geometry={nodes.LARGE_SETTEE018.geometry}
          position={[-15.97, -6.34, 11.52]}
          scale={[0.42, 0.42, 0.42]}
        />
        <mesh
          material={materials.Leather_Seamless_Texture__6690}
          geometry={nodes.LARGE_SETTEE019.geometry}
          position={[-15.97, -6.34, 11.52]}
          scale={[0.42, 0.42, 0.42]}
        />
        <mesh
          material={materials.Leather_Seamless_Texture__6690}
          geometry={nodes.LARGE_SETTEE020.geometry}
          position={[-15.97, -6.34, 11.52]}
          scale={[0.42, 0.42, 0.42]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("../../../togo.glb");
