/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/core/useGLTF";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("../../../untitled.glb");
  return (
    <group
      position={[-0.8, -1, -1]}
      rotation={[0, -Math.PI / 2, 0]}
      ref={group}
      {...props}
      dispose={null}
    >
      <group scale={[0.03, 0.03, 0.03]}>
        <mesh material={materials.Color_D10} geometry={nodes.ID1220.geometry} />
        <mesh
          material={materials["material.001"]}
          geometry={nodes.ID1220_1.geometry}
        />
        <group position={[20.83, 23.99, -2.74]} rotation={[0, 0, 0.06]}>
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_0001.geometry}
            position={[6.69, 1.56, -7.65]}
            rotation={[0, 0, 0.24]}
          />
          <group position={[0.21, 0, 0]} rotation={[0, 0, 0.24]}>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.ID61.geometry}
            />
            <mesh
              material={materials.Color_E05}
              geometry={nodes.ID61_1.geometry}
            />
          </group>
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_2.geometry}
            position={[0.21, 0, -7.65]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_3.geometry}
            position={[6.03, 1.78, -7.15]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_4.geometry}
            position={[6.69, 1.56, 0]}
            rotation={[0, 0, 0.24]}
          />
        </group>
        <group position={[40.84, 30.02, -2.76]} rotation={[0, 0, 0.06]}>
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_0002.geometry}
            position={[6.69, 1.56, -7.65]}
            rotation={[0, 0, 0.24]}
          />
          <group position={[0.21, 0, 0]} rotation={[0, 0, 0.24]}>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.ID61.geometry}
            />
            <mesh
              material={materials.Color_E05}
              geometry={nodes.ID61_1.geometry}
            />
          </group>
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_2001.geometry}
            position={[0.21, 0, -7.65]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_3001.geometry}
            position={[6.03, 1.78, -7.15]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_4001.geometry}
            position={[6.69, 1.56, 0]}
            rotation={[0, 0, 0.24]}
          />
        </group>
        <group position={[11.87, 28.84, -2.76]}>
          <group position={[6.35, 0.12, 0]} rotation={[0, 0, -0.03]}>
            <group position={[1.98, 5.24, 0]} rotation={[0, 0, -1.21]}>
              <mesh
                material={materials.Color_D10}
                geometry={nodes.ID61.geometry}
              />
              <mesh
                material={materials.Color_E05}
                geometry={nodes.ID61_1.geometry}
              />
            </group>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.instance_7.geometry}
              position={[1.98, 5.24, -7.65]}
              rotation={[0, 0, -1.21]}
            />
            <mesh
              material={materials.Color_D10}
              geometry={nodes.instance_6.geometry}
              position={[2.15, 5.84, -7.15]}
              rotation={[0, 0, -1.21]}
            />
            <group
              position={[1.98, 5.24, 0]}
              rotation={[-Math.PI, 0, 1.21]}
              scale={[-1, -1, -1]}
            >
              <mesh
                material={materials.Color_D10}
                geometry={nodes.ID630.geometry}
              />
              <mesh
                material={materials.Color_E05}
                geometry={nodes.ID630_1.geometry}
              />
            </group>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.instance_9.geometry}
              position={[1.98, 5.24, -7.65]}
              rotation={[-Math.PI, 0, 1.21]}
              scale={[-1, -1, -1]}
            />
          </group>
          <group position={[4.13, 6.46, 0]} rotation={[0, 0, -0.03]}>
            <group position={[1.98, 5.24, 0]} rotation={[0, 0, -1.21]}>
              <mesh
                material={materials.Color_D10}
                geometry={nodes.ID61.geometry}
              />
              <mesh
                material={materials.Color_E05}
                geometry={nodes.ID61_1.geometry}
              />
            </group>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.instance_7001.geometry}
              position={[1.98, 5.24, -7.65]}
              rotation={[0, 0, -1.21]}
            />
            <mesh
              material={materials.Color_D10}
              geometry={nodes.instance_6001.geometry}
              position={[2.15, 5.84, -7.15]}
              rotation={[0, 0, -1.21]}
            />
            <group
              position={[1.98, 5.24, 0]}
              rotation={[-Math.PI, 0, 1.21]}
              scale={[-1, -1, -1]}
            >
              <mesh
                material={materials.Color_D10}
                geometry={nodes.ID630.geometry}
              />
              <mesh
                material={materials.Color_E05}
                geometry={nodes.ID630_1.geometry}
              />
            </group>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.instance_9001.geometry}
              position={[1.98, 5.24, -7.65]}
              rotation={[-Math.PI, 0, 1.21]}
              scale={[-1, -1, -1]}
            />
          </group>
          <group position={[1.91, 12.81, 0]} rotation={[0, 0, -0.03]}>
            <group position={[1.98, 5.24, 0]} rotation={[0, 0, -1.21]}>
              <mesh
                material={materials.Color_D10}
                geometry={nodes.ID61.geometry}
              />
              <mesh
                material={materials.Color_E05}
                geometry={nodes.ID61_1.geometry}
              />
            </group>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.instance_7002.geometry}
              position={[1.98, 5.24, -7.65]}
              rotation={[0, 0, -1.21]}
            />
            <mesh
              material={materials.Color_D10}
              geometry={nodes.instance_6002.geometry}
              position={[2.15, 5.84, -7.15]}
              rotation={[0, 0, -1.21]}
            />
            <group
              position={[1.98, 5.24, 0]}
              rotation={[-Math.PI, 0, 1.21]}
              scale={[-1, -1, -1]}
            >
              <mesh
                material={materials.Color_D10}
                geometry={nodes.ID630.geometry}
              />
              <mesh
                material={materials.Color_E05}
                geometry={nodes.ID630_1.geometry}
              />
            </group>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.instance_9002.geometry}
              position={[1.98, 5.24, -7.65]}
              rotation={[-Math.PI, 0, 1.21]}
              scale={[-1, -1, -1]}
            />
          </group>
          <group position={[-0.31, 19.16, 0]} rotation={[0, 0, -0.03]}>
            <group position={[1.98, 5.24, 0]} rotation={[0, 0, -1.21]}>
              <mesh
                material={materials.Color_D10}
                geometry={nodes.ID61.geometry}
              />
              <mesh
                material={materials.Color_E05}
                geometry={nodes.ID61_1.geometry}
              />
            </group>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.instance_7003.geometry}
              position={[1.98, 5.24, -7.65]}
              rotation={[0, 0, -1.21]}
            />
            <mesh
              material={materials.Color_D10}
              geometry={nodes.instance_6003.geometry}
              position={[2.15, 5.84, -7.15]}
              rotation={[0, 0, -1.21]}
            />
            <group
              position={[1.98, 5.24, 0]}
              rotation={[-Math.PI, 0, 1.21]}
              scale={[-1, -1, -1]}
            >
              <mesh
                material={materials.Color_D10}
                geometry={nodes.ID630.geometry}
              />
              <mesh
                material={materials.Color_E05}
                geometry={nodes.ID630_1.geometry}
              />
            </group>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.instance_9003.geometry}
              position={[1.98, 5.24, -7.65]}
              rotation={[-Math.PI, 0, 1.21]}
              scale={[-1, -1, -1]}
            />
          </group>
        </group>
        <group
          position={[18.22, 28.96, -55.12]}
          rotation={[0, 0, 3.11]}
          scale={[-1, -1, -1]}
        >
          <group
            position={[1.98, 5.24, 0]}
            rotation={[-Math.PI, 0, 1.21]}
            scale={[-1, -1, -1]}
          >
            <mesh
              material={materials.Color_D10}
              geometry={nodes.ID61.geometry}
            />
            <mesh
              material={materials.Color_E05}
              geometry={nodes.ID61_1.geometry}
            />
          </group>
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_9004.geometry}
            position={[1.98, 5.24, -7.65]}
            rotation={[-Math.PI, 0, 1.21]}
            scale={[-1, -1, -1]}
          />
          <group position={[1.98, 5.24, 0]} rotation={[0, 0, -1.21]}>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.ID630.geometry}
            />
            <mesh
              material={materials.Color_E05}
              geometry={nodes.ID630_1.geometry}
            />
          </group>
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_6004.geometry}
            position={[2.15, 5.84, -7.15]}
            rotation={[0, 0, -1.21]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_7004.geometry}
            position={[1.98, 5.24, -7.65]}
            rotation={[0, 0, -1.21]}
          />
        </group>
        <group
          position={[40.84, 30.02, -43.39]}
          rotation={[0, 0, -3.08]}
          scale={[-1, -1, -1]}
        >
          <group position={[0.21, 0, 0]} rotation={[0, 0, 0.24]}>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.ID630.geometry}
            />
            <mesh
              material={materials.Color_E05}
              geometry={nodes.ID630_1.geometry}
            />
          </group>
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_3002.geometry}
            position={[6.03, 1.78, -7.15]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_2002.geometry}
            position={[0.21, 0, -7.65]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_0003.geometry}
            position={[6.69, 1.56, -7.65]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_4002.geometry}
            position={[6.69, 1.56, 0]}
            rotation={[0, 0, 0.24]}
          />
        </group>
        <group
          position={[16, 35.3, -55.12]}
          rotation={[0, 0, 3.11]}
          scale={[-1, -1, -1]}
        >
          <group
            position={[1.98, 5.24, 0]}
            rotation={[-Math.PI, 0, 1.21]}
            scale={[-1, -1, -1]}
          >
            <mesh
              material={materials.Color_D10}
              geometry={nodes.ID61.geometry}
            />
            <mesh
              material={materials.Color_E05}
              geometry={nodes.ID61_1.geometry}
            />
          </group>
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_9005.geometry}
            position={[1.98, 5.24, -7.65]}
            rotation={[-Math.PI, 0, 1.21]}
            scale={[-1, -1, -1]}
          />
          <group position={[1.98, 5.24, 0]} rotation={[0, 0, -1.21]}>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.ID630.geometry}
            />
            <mesh
              material={materials.Color_E05}
              geometry={nodes.ID630_1.geometry}
            />
          </group>
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_6005.geometry}
            position={[2.15, 5.84, -7.15]}
            rotation={[0, 0, -1.21]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_7005.geometry}
            position={[1.98, 5.24, -7.65]}
            rotation={[0, 0, -1.21]}
          />
        </group>
        <group
          position={[13.78, 41.65, -55.12]}
          rotation={[0, 0, 3.11]}
          scale={[-1, -1, -1]}
        >
          <group
            position={[1.98, 5.24, 0]}
            rotation={[-Math.PI, 0, 1.21]}
            scale={[-1, -1, -1]}
          >
            <mesh
              material={materials.Color_D10}
              geometry={nodes.ID61.geometry}
            />
            <mesh
              material={materials.Color_E05}
              geometry={nodes.ID61_1.geometry}
            />
          </group>
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_9006.geometry}
            position={[1.98, 5.24, -7.65]}
            rotation={[-Math.PI, 0, 1.21]}
            scale={[-1, -1, -1]}
          />
          <group position={[1.98, 5.24, 0]} rotation={[0, 0, -1.21]}>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.ID630.geometry}
            />
            <mesh
              material={materials.Color_E05}
              geometry={nodes.ID630_1.geometry}
            />
          </group>
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_6006.geometry}
            position={[2.15, 5.84, -7.15]}
            rotation={[0, 0, -1.21]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_7006.geometry}
            position={[1.98, 5.24, -7.65]}
            rotation={[0, 0, -1.21]}
          />
        </group>
        <group
          position={[34.17, 28.01, -55.13]}
          rotation={[0, 0, -3.08]}
          scale={[-1, -1, -1]}
        >
          <group position={[0.21, 0, 0]} rotation={[0, 0, 0.24]}>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.ID630.geometry}
            />
            <mesh
              material={materials.Color_E05}
              geometry={nodes.ID630_1.geometry}
            />
          </group>
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_3003.geometry}
            position={[6.03, 1.78, -7.15]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_2003.geometry}
            position={[0.21, 0, -7.65]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_0004.geometry}
            position={[6.69, 1.56, -7.65]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_4003.geometry}
            position={[6.69, 1.56, 0]}
            rotation={[0, 0, 0.24]}
          />
        </group>
        <group position={[11.87, 28.84, -15.11]}>
          <group position={[6.35, 0.12, 0]} rotation={[0, 0, -0.03]}>
            <group position={[1.98, 5.24, 0]} rotation={[0, 0, -1.21]}>
              <mesh
                material={materials.Color_D10}
                geometry={nodes.ID61.geometry}
              />
              <mesh
                material={materials.Color_E05}
                geometry={nodes.ID61_1.geometry}
              />
            </group>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.instance_7007.geometry}
              position={[1.98, 5.24, -7.65]}
              rotation={[0, 0, -1.21]}
            />
            <mesh
              material={materials.Color_D10}
              geometry={nodes.instance_6007.geometry}
              position={[2.15, 5.84, -7.15]}
              rotation={[0, 0, -1.21]}
            />
            <group
              position={[1.98, 5.24, 0]}
              rotation={[-Math.PI, 0, 1.21]}
              scale={[-1, -1, -1]}
            >
              <mesh
                material={materials.Color_D10}
                geometry={nodes.ID630.geometry}
              />
              <mesh
                material={materials.Color_E05}
                geometry={nodes.ID630_1.geometry}
              />
            </group>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.instance_9007.geometry}
              position={[1.98, 5.24, -7.65]}
              rotation={[-Math.PI, 0, 1.21]}
              scale={[-1, -1, -1]}
            />
          </group>
          <group position={[4.13, 6.46, 0]} rotation={[0, 0, -0.03]}>
            <group position={[1.98, 5.24, 0]} rotation={[0, 0, -1.21]}>
              <mesh
                material={materials.Color_D10}
                geometry={nodes.ID61.geometry}
              />
              <mesh
                material={materials.Color_E05}
                geometry={nodes.ID61_1.geometry}
              />
            </group>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.instance_7008.geometry}
              position={[1.98, 5.24, -7.65]}
              rotation={[0, 0, -1.21]}
            />
            <mesh
              material={materials.Color_D10}
              geometry={nodes.instance_6008.geometry}
              position={[2.15, 5.84, -7.15]}
              rotation={[0, 0, -1.21]}
            />
            <group
              position={[1.98, 5.24, 0]}
              rotation={[-Math.PI, 0, 1.21]}
              scale={[-1, -1, -1]}
            >
              <mesh
                material={materials.Color_D10}
                geometry={nodes.ID630.geometry}
              />
              <mesh
                material={materials.Color_E05}
                geometry={nodes.ID630_1.geometry}
              />
            </group>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.instance_9008.geometry}
              position={[1.98, 5.24, -7.65]}
              rotation={[-Math.PI, 0, 1.21]}
              scale={[-1, -1, -1]}
            />
          </group>
          <group position={[1.91, 12.81, 0]} rotation={[0, 0, -0.03]}>
            <group position={[1.98, 5.24, 0]} rotation={[0, 0, -1.21]}>
              <mesh
                material={materials.Color_D10}
                geometry={nodes.ID61.geometry}
              />
              <mesh
                material={materials.Color_E05}
                geometry={nodes.ID61_1.geometry}
              />
            </group>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.instance_7009.geometry}
              position={[1.98, 5.24, -7.65]}
              rotation={[0, 0, -1.21]}
            />
            <mesh
              material={materials.Color_D10}
              geometry={nodes.instance_6009.geometry}
              position={[2.15, 5.84, -7.15]}
              rotation={[0, 0, -1.21]}
            />
            <group
              position={[1.98, 5.24, 0]}
              rotation={[-Math.PI, 0, 1.21]}
              scale={[-1, -1, -1]}
            >
              <mesh
                material={materials.Color_D10}
                geometry={nodes.ID630.geometry}
              />
              <mesh
                material={materials.Color_E05}
                geometry={nodes.ID630_1.geometry}
              />
            </group>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.instance_9009.geometry}
              position={[1.98, 5.24, -7.65]}
              rotation={[-Math.PI, 0, 1.21]}
              scale={[-1, -1, -1]}
            />
          </group>
          <group position={[-0.31, 19.16, 0]} rotation={[0, 0, -0.03]}>
            <group position={[1.98, 5.24, 0]} rotation={[0, 0, -1.21]}>
              <mesh
                material={materials.Color_D10}
                geometry={nodes.ID61.geometry}
              />
              <mesh
                material={materials.Color_E05}
                geometry={nodes.ID61_1.geometry}
              />
            </group>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.instance_7010.geometry}
              position={[1.98, 5.24, -7.65]}
              rotation={[0, 0, -1.21]}
            />
            <mesh
              material={materials.Color_D10}
              geometry={nodes.instance_6010.geometry}
              position={[2.15, 5.84, -7.15]}
              rotation={[0, 0, -1.21]}
            />
            <group
              position={[1.98, 5.24, 0]}
              rotation={[-Math.PI, 0, 1.21]}
              scale={[-1, -1, -1]}
            >
              <mesh
                material={materials.Color_D10}
                geometry={nodes.ID630.geometry}
              />
              <mesh
                material={materials.Color_E05}
                geometry={nodes.ID630_1.geometry}
              />
            </group>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.instance_9010.geometry}
              position={[1.98, 5.24, -7.65]}
              rotation={[-Math.PI, 0, 1.21]}
              scale={[-1, -1, -1]}
            />
          </group>
        </group>
        <group
          position={[34.17, 28.01, -30.43]}
          rotation={[0, 0, -3.08]}
          scale={[-1, -1, -1]}
        >
          <group position={[0.21, 0, 0]} rotation={[0, 0, 0.24]}>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.ID630.geometry}
            />
            <mesh
              material={materials.Color_E05}
              geometry={nodes.ID630_1.geometry}
            />
          </group>
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_3004.geometry}
            position={[6.03, 1.78, -7.15]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_2004.geometry}
            position={[0.21, 0, -7.65]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_0005.geometry}
            position={[6.69, 1.56, -7.65]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_4004.geometry}
            position={[6.69, 1.56, 0]}
            rotation={[0, 0, 0.24]}
          />
        </group>
        <group position={[27.5, 26, -2.75]} rotation={[0, 0, 0.06]}>
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_0006.geometry}
            position={[6.69, 1.56, -7.65]}
            rotation={[0, 0, 0.24]}
          />
          <group position={[0.21, 0, 0]} rotation={[0, 0, 0.24]}>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.ID61.geometry}
            />
            <mesh
              material={materials.Color_E05}
              geometry={nodes.ID61_1.geometry}
            />
          </group>
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_2005.geometry}
            position={[0.21, 0, -7.65]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_3005.geometry}
            position={[6.03, 1.78, -7.15]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_4005.geometry}
            position={[6.69, 1.56, 0]}
            rotation={[0, 0, 0.24]}
          />
        </group>
        <group
          position={[27.5, 26, -30.42]}
          rotation={[0, 0, -3.08]}
          scale={[-1, -1, -1]}
        >
          <group position={[0.21, 0, 0]} rotation={[0, 0, 0.24]}>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.ID630.geometry}
            />
            <mesh
              material={materials.Color_E05}
              geometry={nodes.ID630_1.geometry}
            />
          </group>
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_3006.geometry}
            position={[6.03, 1.78, -7.15]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_2006.geometry}
            position={[0.21, 0, -7.65]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_0007.geometry}
            position={[6.69, 1.56, -7.65]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_4006.geometry}
            position={[6.69, 1.56, 0]}
            rotation={[0, 0, 0.24]}
          />
        </group>
        <group
          position={[34.17, 28.01, -43.38]}
          rotation={[0, 0, -3.08]}
          scale={[-1, -1, -1]}
        >
          <group position={[0.21, 0, 0]} rotation={[0, 0, 0.24]}>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.ID630.geometry}
            />
            <mesh
              material={materials.Color_E05}
              geometry={nodes.ID630_1.geometry}
            />
          </group>
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_3007.geometry}
            position={[6.03, 1.78, -7.15]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_2007.geometry}
            position={[0.21, 0, -7.65]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_0008.geometry}
            position={[6.69, 1.56, -7.65]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_4007.geometry}
            position={[6.69, 1.56, 0]}
            rotation={[0, 0, 0.24]}
          />
        </group>
        <group
          position={[40.84, 30.02, -30.43]}
          rotation={[0, 0, -3.08]}
          scale={[-1, -1, -1]}
        >
          <group position={[0.21, 0, 0]} rotation={[0, 0, 0.24]}>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.ID630.geometry}
            />
            <mesh
              material={materials.Color_E05}
              geometry={nodes.ID630_1.geometry}
            />
          </group>
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_3008.geometry}
            position={[6.03, 1.78, -7.15]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_2008.geometry}
            position={[0.21, 0, -7.65]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_0009.geometry}
            position={[6.69, 1.56, -7.65]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_4008.geometry}
            position={[6.69, 1.56, 0]}
            rotation={[0, 0, 0.24]}
          />
        </group>
        <group
          position={[27.5, 26, -43.38]}
          rotation={[0, 0, -3.08]}
          scale={[-1, -1, -1]}
        >
          <group position={[0.21, 0, 0]} rotation={[0, 0, 0.24]}>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.ID630.geometry}
            />
            <mesh
              material={materials.Color_E05}
              geometry={nodes.ID630_1.geometry}
            />
          </group>
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_3009.geometry}
            position={[6.03, 1.78, -7.15]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_2009.geometry}
            position={[0.21, 0, -7.65]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_0010.geometry}
            position={[6.69, 1.56, -7.65]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_4009.geometry}
            position={[6.69, 1.56, 0]}
            rotation={[0, 0, 0.24]}
          />
        </group>
        <group
          position={[20.83, 23.99, -43.37]}
          rotation={[0, 0, -3.08]}
          scale={[-1, -1, -1]}
        >
          <group position={[0.21, 0, 0]} rotation={[0, 0, 0.24]}>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.ID630.geometry}
            />
            <mesh
              material={materials.Color_E05}
              geometry={nodes.ID630_1.geometry}
            />
          </group>
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_3010.geometry}
            position={[6.03, 1.78, -7.15]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_2010.geometry}
            position={[0.21, 0, -7.65]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_0011.geometry}
            position={[6.69, 1.56, -7.65]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_4010.geometry}
            position={[6.69, 1.56, 0]}
            rotation={[0, 0, 0.24]}
          />
        </group>
        <group position={[11.87, 28.84, -27.46]}>
          <group position={[6.35, 0.12, 0]} rotation={[0, 0, -0.03]}>
            <group position={[1.98, 5.24, 0]} rotation={[0, 0, -1.21]}>
              <mesh
                material={materials.Color_D10}
                geometry={nodes.ID61.geometry}
              />
              <mesh
                material={materials.Color_E05}
                geometry={nodes.ID61_1.geometry}
              />
            </group>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.instance_7011.geometry}
              position={[1.98, 5.24, -7.65]}
              rotation={[0, 0, -1.21]}
            />
            <mesh
              material={materials.Color_D10}
              geometry={nodes.instance_6011.geometry}
              position={[2.15, 5.84, -7.15]}
              rotation={[0, 0, -1.21]}
            />
            <group
              position={[1.98, 5.24, 0]}
              rotation={[-Math.PI, 0, 1.21]}
              scale={[-1, -1, -1]}
            >
              <mesh
                material={materials.Color_D10}
                geometry={nodes.ID630.geometry}
              />
              <mesh
                material={materials.Color_E05}
                geometry={nodes.ID630_1.geometry}
              />
            </group>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.instance_9011.geometry}
              position={[1.98, 5.24, -7.65]}
              rotation={[-Math.PI, 0, 1.21]}
              scale={[-1, -1, -1]}
            />
          </group>
          <group position={[4.13, 6.46, 0]} rotation={[0, 0, -0.03]}>
            <group position={[1.98, 5.24, 0]} rotation={[0, 0, -1.21]}>
              <mesh
                material={materials.Color_D10}
                geometry={nodes.ID61.geometry}
              />
              <mesh
                material={materials.Color_E05}
                geometry={nodes.ID61_1.geometry}
              />
            </group>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.instance_7012.geometry}
              position={[1.98, 5.24, -7.65]}
              rotation={[0, 0, -1.21]}
            />
            <mesh
              material={materials.Color_D10}
              geometry={nodes.instance_6012.geometry}
              position={[2.15, 5.84, -7.15]}
              rotation={[0, 0, -1.21]}
            />
            <group
              position={[1.98, 5.24, 0]}
              rotation={[-Math.PI, 0, 1.21]}
              scale={[-1, -1, -1]}
            >
              <mesh
                material={materials.Color_D10}
                geometry={nodes.ID630.geometry}
              />
              <mesh
                material={materials.Color_E05}
                geometry={nodes.ID630_1.geometry}
              />
            </group>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.instance_9012.geometry}
              position={[1.98, 5.24, -7.65]}
              rotation={[-Math.PI, 0, 1.21]}
              scale={[-1, -1, -1]}
            />
          </group>
          <group position={[1.91, 12.81, 0]} rotation={[0, 0, -0.03]}>
            <group position={[1.98, 5.24, 0]} rotation={[0, 0, -1.21]}>
              <mesh
                material={materials.Color_D10}
                geometry={nodes.ID61.geometry}
              />
              <mesh
                material={materials.Color_E05}
                geometry={nodes.ID61_1.geometry}
              />
            </group>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.instance_7013.geometry}
              position={[1.98, 5.24, -7.65]}
              rotation={[0, 0, -1.21]}
            />
            <mesh
              material={materials.Color_D10}
              geometry={nodes.instance_6013.geometry}
              position={[2.15, 5.84, -7.15]}
              rotation={[0, 0, -1.21]}
            />
            <group
              position={[1.98, 5.24, 0]}
              rotation={[-Math.PI, 0, 1.21]}
              scale={[-1, -1, -1]}
            >
              <mesh
                material={materials.Color_D10}
                geometry={nodes.ID630.geometry}
              />
              <mesh
                material={materials.Color_E05}
                geometry={nodes.ID630_1.geometry}
              />
            </group>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.instance_9013.geometry}
              position={[1.98, 5.24, -7.65]}
              rotation={[-Math.PI, 0, 1.21]}
              scale={[-1, -1, -1]}
            />
          </group>
          <group position={[-0.31, 19.16, 0]} rotation={[0, 0, -0.03]}>
            <group position={[1.98, 5.24, 0]} rotation={[0, 0, -1.21]}>
              <mesh
                material={materials.Color_D10}
                geometry={nodes.ID61.geometry}
              />
              <mesh
                material={materials.Color_E05}
                geometry={nodes.ID61_1.geometry}
              />
            </group>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.instance_7014.geometry}
              position={[1.98, 5.24, -7.65]}
              rotation={[0, 0, -1.21]}
            />
            <mesh
              material={materials.Color_D10}
              geometry={nodes.instance_6014.geometry}
              position={[2.15, 5.84, -7.15]}
              rotation={[0, 0, -1.21]}
            />
            <group
              position={[1.98, 5.24, 0]}
              rotation={[-Math.PI, 0, 1.21]}
              scale={[-1, -1, -1]}
            >
              <mesh
                material={materials.Color_D10}
                geometry={nodes.ID630.geometry}
              />
              <mesh
                material={materials.Color_E05}
                geometry={nodes.ID630_1.geometry}
              />
            </group>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.instance_9014.geometry}
              position={[1.98, 5.24, -7.65]}
              rotation={[-Math.PI, 0, 1.21]}
              scale={[-1, -1, -1]}
            />
          </group>
        </group>
        <group
          position={[20.83, 23.99, -30.42]}
          rotation={[0, 0, -3.08]}
          scale={[-1, -1, -1]}
        >
          <group position={[0.21, 0, 0]} rotation={[0, 0, 0.24]}>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.ID630.geometry}
            />
            <mesh
              material={materials.Color_E05}
              geometry={nodes.ID630_1.geometry}
            />
          </group>
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_3011.geometry}
            position={[6.03, 1.78, -7.15]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_2011.geometry}
            position={[0.21, 0, -7.65]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_0012.geometry}
            position={[6.69, 1.56, -7.65]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_4011.geometry}
            position={[6.69, 1.56, 0]}
            rotation={[0, 0, 0.24]}
          />
        </group>
        <group
          position={[20.83, 23.99, -55.12]}
          rotation={[0, 0, -3.08]}
          scale={[-1, -1, -1]}
        >
          <group position={[0.21, 0, 0]} rotation={[0, 0, 0.24]}>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.ID630.geometry}
            />
            <mesh
              material={materials.Color_E05}
              geometry={nodes.ID630_1.geometry}
            />
          </group>
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_3012.geometry}
            position={[6.03, 1.78, -7.15]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_2012.geometry}
            position={[0.21, 0, -7.65]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_0013.geometry}
            position={[6.69, 1.56, -7.65]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_4012.geometry}
            position={[6.69, 1.56, 0]}
            rotation={[0, 0, 0.24]}
          />
        </group>
        <group
          position={[11.56, 48, -55.12]}
          rotation={[0, 0, 3.11]}
          scale={[-1, -1, -1]}
        >
          <group
            position={[1.98, 5.24, 0]}
            rotation={[-Math.PI, 0, 1.21]}
            scale={[-1, -1, -1]}
          >
            <mesh
              material={materials.Color_D10}
              geometry={nodes.ID61.geometry}
            />
            <mesh
              material={materials.Color_E05}
              geometry={nodes.ID61_1.geometry}
            />
          </group>
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_9015.geometry}
            position={[1.98, 5.24, -7.65]}
            rotation={[-Math.PI, 0, 1.21]}
            scale={[-1, -1, -1]}
          />
          <group position={[1.98, 5.24, 0]} rotation={[0, 0, -1.21]}>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.ID630.geometry}
            />
            <mesh
              material={materials.Color_E05}
              geometry={nodes.ID630_1.geometry}
            />
          </group>
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_6015.geometry}
            position={[2.15, 5.84, -7.15]}
            rotation={[0, 0, -1.21]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_7015.geometry}
            position={[1.98, 5.24, -7.65]}
            rotation={[0, 0, -1.21]}
          />
        </group>
        <group position={[34.17, 28.01, -2.75]} rotation={[0, 0, 0.06]}>
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_0014.geometry}
            position={[6.69, 1.56, -7.65]}
            rotation={[0, 0, 0.24]}
          />
          <group position={[0.21, 0, 0]} rotation={[0, 0, 0.24]}>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.ID61.geometry}
            />
            <mesh
              material={materials.Color_E05}
              geometry={nodes.ID61_1.geometry}
            />
          </group>
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_2013.geometry}
            position={[0.21, 0, -7.65]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_3013.geometry}
            position={[6.03, 1.78, -7.15]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_4013.geometry}
            position={[6.69, 1.56, 0]}
            rotation={[0, 0, 0.24]}
          />
        </group>
        <group
          position={[27.5, 26, -55.12]}
          rotation={[0, 0, -3.08]}
          scale={[-1, -1, -1]}
        >
          <group position={[0.21, 0, 0]} rotation={[0, 0, 0.24]}>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.ID630.geometry}
            />
            <mesh
              material={materials.Color_E05}
              geometry={nodes.ID630_1.geometry}
            />
          </group>
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_3014.geometry}
            position={[6.03, 1.78, -7.15]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_2014.geometry}
            position={[0.21, 0, -7.65]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_0015.geometry}
            position={[6.69, 1.56, -7.65]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_4014.geometry}
            position={[6.69, 1.56, 0]}
            rotation={[0, 0, 0.24]}
          />
        </group>
        <group
          position={[40.84, 30.02, -55.13]}
          rotation={[0, 0, -3.08]}
          scale={[-1, -1, -1]}
        >
          <group position={[0.21, 0, 0]} rotation={[0, 0, 0.24]}>
            <mesh
              material={materials.Color_D10}
              geometry={nodes.ID630.geometry}
            />
            <mesh
              material={materials.Color_E05}
              geometry={nodes.ID630_1.geometry}
            />
          </group>
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_3015.geometry}
            position={[6.03, 1.78, -7.15]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_2015.geometry}
            position={[0.21, 0, -7.65]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_0016.geometry}
            position={[6.69, 1.56, -7.65]}
            rotation={[0, 0, 0.24]}
          />
          <mesh
            material={materials.Color_D10}
            geometry={nodes.instance_4015.geometry}
            position={[6.69, 1.56, 0]}
            rotation={[0, 0, 0.24]}
          />
        </group>
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_0.geometry}
          position={[19.63, 14.48, -15.18]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_0001.geometry}
          position={[19.63, 14.48, -15.18]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_0002.geometry}
          position={[19.63, 14.48, -15.18]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_0003.geometry}
          position={[19.63, 14.48, -15.18]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_0004.geometry}
          position={[19.63, 14.48, -15.18]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_10.geometry}
          position={[19.63, 14.48, -27.6]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_10001.geometry}
          position={[19.63, 14.48, -27.6]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_10002.geometry}
          position={[19.63, 14.48, -27.6]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_10003.geometry}
          position={[19.63, 14.48, -27.6]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_10004.geometry}
          position={[19.63, 14.48, -27.6]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_11.geometry}
          position={[19.63, 14.48, -21.39]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_11001.geometry}
          position={[19.63, 14.48, -21.39]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_11002.geometry}
          position={[19.63, 14.48, -21.39]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_11003.geometry}
          position={[19.63, 14.48, -21.39]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_11004.geometry}
          position={[19.63, 14.48, -21.39]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_18.geometry}
          position={[19.63, 14.48, -52.44]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_18001.geometry}
          position={[19.63, 14.48, -52.44]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_18002.geometry}
          position={[19.63, 14.48, -52.44]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_18003.geometry}
          position={[19.63, 14.48, -52.44]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_18004.geometry}
          position={[19.63, 14.48, -52.44]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_2.geometry}
          position={[1.13, 14.48, -12.04]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_2001.geometry}
          position={[1.13, 14.48, -12.04]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_2002.geometry}
          position={[1.13, 14.48, -12.04]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_2003.geometry}
          position={[1.13, 14.48, -12.04]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_2004.geometry}
          position={[1.13, 14.48, -12.04]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_2005.geometry}
          position={[1.13, 14.48, -12.04]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_2006.geometry}
          position={[1.13, 14.48, -12.04]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_2007.geometry}
          position={[1.13, 14.48, -12.04]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_27.geometry}
          position={[1.13, 14.48, -49.18]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_27001.geometry}
          position={[1.13, 14.48, -49.18]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_27002.geometry}
          position={[1.13, 14.48, -49.18]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_27003.geometry}
          position={[1.13, 14.48, -49.18]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_27004.geometry}
          position={[1.13, 14.48, -49.18]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_27005.geometry}
          position={[1.13, 14.48, -49.18]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_27006.geometry}
          position={[1.13, 14.48, -49.18]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_27007.geometry}
          position={[1.13, 14.48, -49.18]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_28.geometry}
          position={[4.43, 17.49, -2.76]}
        />
        <group position={[4.43, 17.49, -2.76]}>
          <mesh
            material={materials.Color_D10}
            geometry={nodes.ID875.geometry}
          />
          <mesh
            material={materials.Color_000}
            geometry={nodes.ID875_1.geometry}
          />
        </group>
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_28002.geometry}
          position={[4.43, 17.49, -2.76]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_3.geometry}
          position={[1.13, 14.48, -18.23]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_3001.geometry}
          position={[1.13, 14.48, -18.23]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_3002.geometry}
          position={[1.13, 14.48, -18.23]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_3003.geometry}
          position={[1.13, 14.48, -18.23]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_3004.geometry}
          position={[1.13, 14.48, -18.23]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_3005.geometry}
          position={[1.13, 14.48, -18.23]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_3006.geometry}
          position={[1.13, 14.48, -18.23]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_3007.geometry}
          position={[1.13, 14.48, -18.23]}
        />
        <group
          position={[2.49, 55.67, -6.64]}
          rotation={[Math.PI / 2, 0, -1.57]}
        >
          <mesh
            material={materials.Color_D10}
            geometry={nodes.ID918.geometry}
          />
          <mesh
            material={materials.Color_000}
            geometry={nodes.ID918_1.geometry}
          />
        </group>
        <group
          position={[2.49, 55.67, -6.64]}
          rotation={[Math.PI / 2, 0, -1.57]}
        >
          <mesh
            material={materials.Color_D10}
            geometry={nodes.ID926.geometry}
          />
          <mesh
            material={materials.Color_000}
            geometry={nodes.ID926_1.geometry}
          />
        </group>
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_38.geometry}
          position={[1.13, 14.48, -36.8]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_38001.geometry}
          position={[1.13, 14.48, -36.8]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_38002.geometry}
          position={[1.13, 14.48, -36.8]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_38003.geometry}
          position={[1.13, 14.48, -36.8]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_38004.geometry}
          position={[1.13, 14.48, -36.8]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_38005.geometry}
          position={[1.13, 14.48, -36.8]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_38006.geometry}
          position={[1.13, 14.48, -36.8]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_38007.geometry}
          position={[1.13, 14.48, -36.8]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_39.geometry}
          position={[1.13, 14.48, -42.99]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_39001.geometry}
          position={[1.13, 14.48, -42.99]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_39002.geometry}
          position={[1.13, 14.48, -42.99]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_39003.geometry}
          position={[1.13, 14.48, -42.99]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_39004.geometry}
          position={[1.13, 14.48, -42.99]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_39005.geometry}
          position={[1.13, 14.48, -42.99]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_39006.geometry}
          position={[1.13, 14.48, -42.99]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_39007.geometry}
          position={[1.13, 14.48, -42.99]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_4.geometry}
          position={[1.13, 14.48, -30.61]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_4001.geometry}
          position={[1.13, 14.48, -30.61]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_4002.geometry}
          position={[1.13, 14.48, -30.61]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_4003.geometry}
          position={[1.13, 14.48, -30.61]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_4004.geometry}
          position={[1.13, 14.48, -30.61]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_4005.geometry}
          position={[1.13, 14.48, -30.61]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_4006.geometry}
          position={[1.13, 14.48, -30.61]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_4007.geometry}
          position={[1.13, 14.48, -30.61]}
        />
        <group position={[1.13, 14.48, -24.42]}>
          <mesh
            material={materials.Color_D10}
            geometry={nodes.ID1126.geometry}
          />
          <mesh
            material={materials.Color_000}
            geometry={nodes.ID1126_1.geometry}
          />
        </group>
        <group position={[1.13, 14.48, -24.42]}>
          <mesh
            material={materials.Color_D10}
            geometry={nodes.ID1134.geometry}
          />
          <mesh
            material={materials.Color_000}
            geometry={nodes.ID1134_1.geometry}
          />
        </group>
        <group position={[1.13, 14.48, -24.42]}>
          <mesh
            material={materials.Color_D10}
            geometry={nodes.ID1142.geometry}
          />
          <mesh
            material={materials.Color_000}
            geometry={nodes.ID1142_1.geometry}
          />
        </group>
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_43003.geometry}
          position={[1.13, 14.48, -24.42]}
        />
        <group position={[1.13, 14.48, -24.42]}>
          <mesh
            material={materials.Color_D10}
            geometry={nodes.ID1158.geometry}
          />
          <mesh
            material={materials.Color_000}
            geometry={nodes.ID1158_1.geometry}
          />
        </group>
        <group position={[1.13, 14.48, -24.42]}>
          <mesh
            material={materials.Color_D10}
            geometry={nodes.ID1166.geometry}
          />
          <mesh
            material={materials.Color_000}
            geometry={nodes.ID1166_1.geometry}
          />
        </group>
        <group position={[1.13, 14.48, -24.42]}>
          <mesh
            material={materials.Color_D10}
            geometry={nodes.ID1174.geometry}
          />
          <mesh
            material={materials.Color_000}
            geometry={nodes.ID1174_1.geometry}
          />
        </group>
        <group position={[1.13, 14.48, -24.42]}>
          <mesh
            material={materials.Color_D10}
            geometry={nodes.ID1182.geometry}
          />
          <mesh
            material={materials.Color_000}
            geometry={nodes.ID1182_1.geometry}
          />
        </group>
        <group position={[1.13, 14.48, -24.42]}>
          <mesh
            material={materials.Color_D10}
            geometry={nodes.ID1190.geometry}
          />
          <mesh
            material={materials.Color_000}
            geometry={nodes.ID1190_1.geometry}
          />
        </group>
        <group position={[1.13, 14.48, -24.42]}>
          <mesh
            material={materials.Color_D10}
            geometry={nodes.ID1198.geometry}
          />
          <mesh
            material={materials.Color_000}
            geometry={nodes.ID1198_1.geometry}
          />
        </group>
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_43010.geometry}
          position={[1.13, 14.48, -24.42]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_5.geometry}
          position={[19.63, 14.48, -8.97]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_5001.geometry}
          position={[19.63, 14.48, -8.97]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_5002.geometry}
          position={[19.63, 14.48, -8.97]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_5003.geometry}
          position={[19.63, 14.48, -8.97]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_5004.geometry}
          position={[19.63, 14.48, -8.97]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_6.geometry}
          position={[19.63, 14.48, -2.76]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_6001.geometry}
          position={[19.63, 14.48, -2.76]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_6002.geometry}
          position={[19.63, 14.48, -2.76]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_6003.geometry}
          position={[19.63, 14.48, -2.76]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_6004.geometry}
          position={[19.63, 14.48, -2.76]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_6005.geometry}
          position={[19.63, 14.48, -2.76]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_6006.geometry}
          position={[19.63, 14.48, -2.76]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_6007.geometry}
          position={[19.63, 14.48, -2.76]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_6008.geometry}
          position={[19.63, 14.48, -2.76]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_7.geometry}
          position={[19.63, 14.48, -33.81]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_7001.geometry}
          position={[19.63, 14.48, -33.81]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_7002.geometry}
          position={[19.63, 14.48, -33.81]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_7003.geometry}
          position={[19.63, 14.48, -33.81]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_7004.geometry}
          position={[19.63, 14.48, -33.81]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_8.geometry}
          position={[19.63, 14.48, -40.02]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_8001.geometry}
          position={[19.63, 14.48, -40.02]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_8002.geometry}
          position={[19.63, 14.48, -40.02]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_8003.geometry}
          position={[19.63, 14.48, -40.02]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_8004.geometry}
          position={[19.63, 14.48, -40.02]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_9.geometry}
          position={[19.63, 14.48, -46.23]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_9001.geometry}
          position={[19.63, 14.48, -46.23]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_9002.geometry}
          position={[19.63, 14.48, -46.23]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_9003.geometry}
          position={[19.63, 14.48, -46.23]}
        />
        <mesh
          material={materials.Color_D10}
          geometry={nodes.group_9004.geometry}
          position={[19.63, 14.48, -46.23]}
        />
      </group>
      <group scale={[0.03, 0.03, 0.03]}>
        <mesh material={materials.Color_D10} geometry={nodes.ID1230.geometry} />
        <mesh
          material={materials.Metal_Corrogated_Shiny}
          geometry={nodes.ID1230_1.geometry}
        />
      </group>
      <mesh
        material={materials.Color_D10}
        geometry={nodes.SketchUp002.geometry}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        material={materials.Color_D10}
        geometry={nodes.SketchUp003.geometry}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        material={materials.Color_D10}
        geometry={nodes.SketchUp004.geometry}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        material={materials.Color_D10}
        geometry={nodes.SketchUp005.geometry}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        material={materials.Color_D10}
        geometry={nodes.SketchUp006.geometry}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        material={materials.Color_D10}
        geometry={nodes.SketchUp007.geometry}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        material={materials.Color_D10}
        geometry={nodes.SketchUp008.geometry}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        material={materials.Color_D10}
        geometry={nodes.SketchUp009.geometry}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        material={materials.Color_D10}
        geometry={nodes.SketchUp010.geometry}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        material={materials.Color_D10}
        geometry={nodes.SketchUp011.geometry}
        scale={[0.03, 0.03, 0.03]}
      />
      <group scale={[0.03, 0.03, 0.03]}>
        <mesh material={materials.Color_D10} geometry={nodes.ID1325.geometry} />
        <mesh
          material={materials["material.001"]}
          geometry={nodes.ID1325_1.geometry}
        />
      </group>
      <mesh
        material={materials.Color_D10}
        geometry={nodes.SketchUp013.geometry}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        material={materials.Color_D10}
        geometry={nodes.SketchUp014.geometry}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        material={materials.Color_D10}
        geometry={nodes.SketchUp015.geometry}
        scale={[0.03, 0.03, 0.03]}
      />
      <group scale={[0.03, 0.03, 0.03]}>
        <mesh material={materials.Color_D10} geometry={nodes.ID1357.geometry} />
        <mesh
          material={materials["material.001"]}
          geometry={nodes.ID1357_1.geometry}
        />
      </group>
      <mesh
        material={materials.Color_D10}
        geometry={nodes.SketchUp017.geometry}
        scale={[0.03, 0.03, 0.03]}
      />
    </group>
  );
}

useGLTF.preload("../../../untitled.glb");
