/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Render - City (https://sketchfab.com/greshnovk)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/1c4d14c0e90b49018475c335aebc425b
title: Wassily DFA 24
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/core/useGLTF";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("../../../scene.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[-25.24, 46.62, 6.56]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[0.2, 0, -46.62]}>
              <mesh
                material={materials.leather}
                geometry={nodes.skin_leather_0.geometry}
              />
            </group>
          </group>
          <group
            position={[-27.18, 38.32, 6.56]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              material={materials.metal}
              geometry={nodes.rama_metal_0.geometry}
            />
          </group>
          <group position={[-25.04, 0, 6.56]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              material={materials.material}
              geometry={nodes.Nogi_Rub_0.geometry}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("../../../scene.gltf");
