/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/core/useGLTF";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("../../../wirechair.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={[0.03, 0.03, 0.03]}>
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_0.geometry}
          position={[-7.11, -18.08, 6.3]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_10.geometry}
          position={[-7.11, -18.08, -8.92]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_5.geometry}
          position={[6.18, -18.08, 6.3]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_1.geometry}
          position={[-6.86, -17.82, 2.29]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_11.geometry}
          position={[9.73, -2.17, -10.74]}
          rotation={[Math.PI, -1.57, 0]}
          scale={[-1.03, -1.03, -1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_11001.geometry}
          position={[9.73, -2.17, -10.74]}
          rotation={[Math.PI, -1.57, 0]}
          scale={[-1.03, -1.03, -1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_11002.geometry}
          position={[9.73, -2.17, -10.74]}
          rotation={[Math.PI, -1.57, 0]}
          scale={[-1.03, -1.03, -1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_11003.geometry}
          position={[9.73, -2.17, -10.74]}
          rotation={[Math.PI, -1.57, 0]}
          scale={[-1.03, -1.03, -1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_11004.geometry}
          position={[9.73, -2.17, -10.74]}
          rotation={[Math.PI, -1.57, 0]}
          scale={[-1.03, -1.03, -1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_11005.geometry}
          position={[9.73, -2.17, -10.74]}
          rotation={[Math.PI, -1.57, 0]}
          scale={[-1.03, -1.03, -1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_11006.geometry}
          position={[9.73, -2.17, -10.74]}
          rotation={[Math.PI, -1.57, 0]}
          scale={[-1.03, -1.03, -1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_11007.geometry}
          position={[9.73, -2.17, -10.74]}
          rotation={[Math.PI, -1.57, 0]}
          scale={[-1.03, -1.03, -1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_11008.geometry}
          position={[9.73, -2.17, -10.74]}
          rotation={[Math.PI, -1.57, 0]}
          scale={[-1.03, -1.03, -1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_11009.geometry}
          position={[9.73, -2.17, -10.74]}
          rotation={[Math.PI, -1.57, 0]}
          scale={[-1.03, -1.03, -1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_11010.geometry}
          position={[9.73, -2.17, -10.74]}
          rotation={[Math.PI, -1.57, 0]}
          scale={[-1.03, -1.03, -1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_11011.geometry}
          position={[9.73, -2.17, -10.74]}
          rotation={[Math.PI, -1.57, 0]}
          scale={[-1.03, -1.03, -1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_11012.geometry}
          position={[9.73, -2.17, -10.74]}
          rotation={[Math.PI, -1.57, 0]}
          scale={[-1.03, -1.03, -1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_11013.geometry}
          position={[9.73, -2.17, -10.74]}
          rotation={[Math.PI, -1.57, 0]}
          scale={[-1.03, -1.03, -1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_11014.geometry}
          position={[9.73, -2.17, -10.74]}
          rotation={[Math.PI, -1.57, 0]}
          scale={[-1.03, -1.03, -1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_11015.geometry}
          position={[9.73, -2.17, -10.74]}
          rotation={[Math.PI, -1.57, 0]}
          scale={[-1.03, -1.03, -1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_11016.geometry}
          position={[9.73, -2.17, -10.74]}
          rotation={[Math.PI, -1.57, 0]}
          scale={[-1.03, -1.03, -1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_11017.geometry}
          position={[9.73, -2.17, -10.74]}
          rotation={[Math.PI, -1.57, 0]}
          scale={[-1.03, -1.03, -1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_11018.geometry}
          position={[9.73, -2.17, -10.74]}
          rotation={[Math.PI, -1.57, 0]}
          scale={[-1.03, -1.03, -1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_11019.geometry}
          position={[9.73, -2.17, -10.74]}
          rotation={[Math.PI, -1.57, 0]}
          scale={[-1.03, -1.03, -1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_11020.geometry}
          position={[9.73, -2.17, -10.74]}
          rotation={[Math.PI, -1.57, 0]}
          scale={[-1.03, -1.03, -1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_11021.geometry}
          position={[9.73, -2.17, -10.74]}
          rotation={[Math.PI, -1.57, 0]}
          scale={[-1.03, -1.03, -1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_11022.geometry}
          position={[9.73, -2.17, -10.74]}
          rotation={[Math.PI, -1.57, 0]}
          scale={[-1.03, -1.03, -1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_11023.geometry}
          position={[9.73, -2.17, -10.74]}
          rotation={[Math.PI, -1.57, 0]}
          scale={[-1.03, -1.03, -1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_11024.geometry}
          position={[9.73, -2.17, -10.74]}
          rotation={[Math.PI, -1.57, 0]}
          scale={[-1.03, -1.03, -1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_11025.geometry}
          position={[9.73, -2.17, -10.74]}
          rotation={[Math.PI, -1.57, 0]}
          scale={[-1.03, -1.03, -1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_11026.geometry}
          position={[9.73, -2.17, -10.74]}
          rotation={[Math.PI, -1.57, 0]}
          scale={[-1.03, -1.03, -1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_11027.geometry}
          position={[9.73, -2.17, -10.74]}
          rotation={[Math.PI, -1.57, 0]}
          scale={[-1.03, -1.03, -1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_11028.geometry}
          position={[9.73, -2.17, -10.74]}
          rotation={[Math.PI, -1.57, 0]}
          scale={[-1.03, -1.03, -1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_11029.geometry}
          position={[9.73, -2.17, -10.74]}
          rotation={[Math.PI, -1.57, 0]}
          scale={[-1.03, -1.03, -1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_11030.geometry}
          position={[9.73, -2.17, -10.74]}
          rotation={[Math.PI, -1.57, 0]}
          scale={[-1.03, -1.03, -1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_11031.geometry}
          position={[9.73, -2.17, -10.74]}
          rotation={[Math.PI, -1.57, 0]}
          scale={[-1.03, -1.03, -1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_12.geometry}
          position={[-3.1, -2.55, -4.14]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_13.geometry}
          position={[-6.86, -17.82, -8.67]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_14.geometry}
          position={[-2.98, -16.51, -8.34]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_15.geometry}
          position={[-3.59, -8.12, -4.7]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_15001.geometry}
          position={[-3.59, -8.12, -4.7]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_15002.geometry}
          position={[-3.59, -8.12, -4.7]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_15003.geometry}
          position={[-3.59, -8.12, -4.7]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_16.geometry}
          position={[-6.6, -16.51, -8.34]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_2.geometry}
          position={[7.07, -18.08, -8.92]}
          rotation={[Math.PI, -1.57, 0]}
          scale={[-1.03, -1.03, -1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_3.geometry}
          position={[-9.77, -2.17, -10.74]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_3001.geometry}
          position={[-9.77, -2.17, -10.74]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_3002.geometry}
          position={[-9.77, -2.17, -10.74]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_3003.geometry}
          position={[-9.77, -2.17, -10.74]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_3004.geometry}
          position={[-9.77, -2.17, -10.74]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_3005.geometry}
          position={[-9.77, -2.17, -10.74]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_3006.geometry}
          position={[-9.77, -2.17, -10.74]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_3007.geometry}
          position={[-9.77, -2.17, -10.74]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_3008.geometry}
          position={[-9.77, -2.17, -10.74]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_3009.geometry}
          position={[-9.77, -2.17, -10.74]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_3010.geometry}
          position={[-9.77, -2.17, -10.74]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_3011.geometry}
          position={[-9.77, -2.17, -10.74]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_3012.geometry}
          position={[-9.77, -2.17, -10.74]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_3013.geometry}
          position={[-9.77, -2.17, -10.74]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_3014.geometry}
          position={[-9.77, -2.17, -10.74]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_3015.geometry}
          position={[-9.77, -2.17, -10.74]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_3016.geometry}
          position={[-9.77, -2.17, -10.74]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_3017.geometry}
          position={[-9.77, -2.17, -10.74]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_3018.geometry}
          position={[-9.77, -2.17, -10.74]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_3019.geometry}
          position={[-9.77, -2.17, -10.74]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_3020.geometry}
          position={[-9.77, -2.17, -10.74]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_3021.geometry}
          position={[-9.77, -2.17, -10.74]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_3022.geometry}
          position={[-9.77, -2.17, -10.74]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_3023.geometry}
          position={[-9.77, -2.17, -10.74]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_3024.geometry}
          position={[-9.77, -2.17, -10.74]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_3025.geometry}
          position={[-9.77, -2.17, -10.74]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_3026.geometry}
          position={[-9.77, -2.17, -10.74]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_3027.geometry}
          position={[-9.77, -2.17, -10.74]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_3028.geometry}
          position={[-9.77, -2.17, -10.74]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_3029.geometry}
          position={[-9.77, -2.17, -10.74]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_3030.geometry}
          position={[-9.77, -2.17, -10.74]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_3031.geometry}
          position={[-9.77, -2.17, -10.74]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_4.geometry}
          position={[6.68, -16.64, -0.75]}
          rotation={[Math.PI, -1.57, 0]}
          scale={[-1.03, -1.03, -1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_6.geometry}
          position={[6.82, -17.82, 2.29]}
          rotation={[Math.PI, -1.57, 0]}
          scale={[-1.03, -1.03, -1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_7.geometry}
          position={[6.82, -17.82, -8.67]}
          rotation={[Math.PI, -1.57, 0]}
          scale={[-1.03, -1.03, -1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_8.geometry}
          position={[-6.72, -16.64, -0.75]}
          rotation={[0, -1.57, 0]}
          scale={[1.03, 1.03, 1.03]}
        />
        <mesh
          material={materials.material_1}
          geometry={nodes.instance_9.geometry}
          position={[6.55, -16.51, -8.34]}
          rotation={[Math.PI, -1.57, 0]}
          scale={[-1.03, -1.03, -1.03]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("../../../wirechair.glb");
