/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/core/useGLTF";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("../../../wirechair.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-0.22, -0.44, 0.22]} scale={[0.03, 0.03, 0.03]}>
        <group position={[-0.22, -0.44, 0.22]}>
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_0002.geometry}
            position={[16.38, -0.44, -2.38]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_10.geometry}
            position={[1.56, -0.44, -2.38]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_5.geometry}
            position={[16.38, -0.44, -15.32]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_1.geometry}
            position={[12.48, -0.19, -2.62]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_11.geometry}
            position={[-0.22, 15.05, -18.78]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_11001.geometry}
            position={[-0.22, 15.05, -18.78]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_11002.geometry}
            position={[-0.22, 15.05, -18.78]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_11003.geometry}
            position={[-0.22, 15.05, -18.78]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_11004.geometry}
            position={[-0.22, 15.05, -18.78]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_11005.geometry}
            position={[-0.22, 15.05, -18.78]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_11006.geometry}
            position={[-0.22, 15.05, -18.78]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_11007.geometry}
            position={[-0.22, 15.05, -18.78]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_11008.geometry}
            position={[-0.22, 15.05, -18.78]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_11009.geometry}
            position={[-0.22, 15.05, -18.78]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_11010.geometry}
            position={[-0.22, 15.05, -18.78]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_11011.geometry}
            position={[-0.22, 15.05, -18.78]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_11012.geometry}
            position={[-0.22, 15.05, -18.78]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_11013.geometry}
            position={[-0.22, 15.05, -18.78]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_11014.geometry}
            position={[-0.22, 15.05, -18.78]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_11015.geometry}
            position={[-0.22, 15.05, -18.78]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_11016.geometry}
            position={[-0.22, 15.05, -18.78]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_11017.geometry}
            position={[-0.22, 15.05, -18.78]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_11018.geometry}
            position={[-0.22, 15.05, -18.78]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_11019.geometry}
            position={[-0.22, 15.05, -18.78]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_11020.geometry}
            position={[-0.22, 15.05, -18.78]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_11021.geometry}
            position={[-0.22, 15.05, -18.78]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_11022.geometry}
            position={[-0.22, 15.05, -18.78]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_11023.geometry}
            position={[-0.22, 15.05, -18.78]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_11024.geometry}
            position={[-0.22, 15.05, -18.78]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_11025.geometry}
            position={[-0.22, 15.05, -18.78]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_11026.geometry}
            position={[-0.22, 15.05, -18.78]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_11027.geometry}
            position={[-0.22, 15.05, -18.78]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_11028.geometry}
            position={[-0.22, 15.05, -18.78]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_11029.geometry}
            position={[-0.22, 15.05, -18.78]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_11030.geometry}
            position={[-0.22, 15.05, -18.78]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_11031.geometry}
            position={[-0.22, 15.05, -18.78]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_12.geometry}
            position={[6.21, 14.69, -6.28]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_13.geometry}
            position={[1.8, -0.19, -2.62]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_14.geometry}
            position={[2.12, 1.08, -6.4]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_15.geometry}
            position={[5.67, 9.26, -5.8]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_15001.geometry}
            position={[5.67, 9.26, -5.8]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_15002.geometry}
            position={[5.67, 9.26, -5.8]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_15003.geometry}
            position={[5.67, 9.26, -5.8]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_16.geometry}
            position={[2.12, 1.08, -2.87]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_2.geometry}
            position={[1.56, -0.44, -16.18]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_3.geometry}
            position={[-0.22, 15.05, 0.22]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_3001.geometry}
            position={[-0.22, 15.05, 0.22]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_3002.geometry}
            position={[-0.22, 15.05, 0.22]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_3003.geometry}
            position={[-0.22, 15.05, 0.22]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_3004.geometry}
            position={[-0.22, 15.05, 0.22]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_3005.geometry}
            position={[-0.22, 15.05, 0.22]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_3006.geometry}
            position={[-0.22, 15.05, 0.22]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_3007.geometry}
            position={[-0.22, 15.05, 0.22]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_3008.geometry}
            position={[-0.22, 15.05, 0.22]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_3009.geometry}
            position={[-0.22, 15.05, 0.22]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_3010.geometry}
            position={[-0.22, 15.05, 0.22]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_3011.geometry}
            position={[-0.22, 15.05, 0.22]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_3012.geometry}
            position={[-0.22, 15.05, 0.22]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_3013.geometry}
            position={[-0.22, 15.05, 0.22]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_3014.geometry}
            position={[-0.22, 15.05, 0.22]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_3015.geometry}
            position={[-0.22, 15.05, 0.22]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_3016.geometry}
            position={[-0.22, 15.05, 0.22]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_3017.geometry}
            position={[-0.22, 15.05, 0.22]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_3018.geometry}
            position={[-0.22, 15.05, 0.22]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_3019.geometry}
            position={[-0.22, 15.05, 0.22]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_3020.geometry}
            position={[-0.22, 15.05, 0.22]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_3021.geometry}
            position={[-0.22, 15.05, 0.22]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_3022.geometry}
            position={[-0.22, 15.05, 0.22]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_3023.geometry}
            position={[-0.22, 15.05, 0.22]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_3024.geometry}
            position={[-0.22, 15.05, 0.22]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_3025.geometry}
            position={[-0.22, 15.05, 0.22]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_3026.geometry}
            position={[-0.22, 15.05, 0.22]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_3027.geometry}
            position={[-0.22, 15.05, 0.22]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_3028.geometry}
            position={[-0.22, 15.05, 0.22]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_3029.geometry}
            position={[-0.22, 15.05, 0.22]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_3030.geometry}
            position={[-0.22, 15.05, 0.22]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_3031.geometry}
            position={[-0.22, 15.05, 0.22]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_4.geometry}
            position={[9.52, 0.96, -15.81]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_6.geometry}
            position={[12.48, -0.19, -15.94]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_7.geometry}
            position={[1.8, -0.19, -15.94]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_8.geometry}
            position={[9.52, 0.96, -2.75]}
          />
          <mesh
            material={materials["material_1.002"]}
            geometry={nodes.instance_9.geometry}
            position={[2.12, 1.08, -15.68]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1, -1, -1]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("../../../wirechair.glb");
